### DISCUSSION TITLE
about/

### DISCUSSION THREAD

**Discussion by giscus** [Lapis0x0/blog-discussion#1] [Announcements]
# about/

关于

https://www.lapis.cafe/about/

**Comment by Lapis0x0** [comment]
这是一条测试评论

**Comment by xingwangzhe** [comment]
```yaml
      name: 姓王者的博客
      link:  https://xingwangzhe.fun
      img: https://xingwangzhe.fun/images/avatar.webp
      description: 记录学习生活的琐事，或技术文章
```
我已在
```
https://xingwangzhe.fun/links
```
添加友链
